[package]
name = "markdown-web-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "1.0.0-alpha.11"
frontmatter = "0.4.0"
yaml-rust = "0.4"
